Create Table Categorias(
	Id_Categoria varchar(255) PRIMARY KEY,
	Nombre varchar(255)
);

Create Table Preguntas(
	Id_Pregunta int NOT NULL AUTO_INCREMENT,
	Id_Categoria varchar(255),
	Pregunta varchar(255),
   	PRIMARY KEY(Id_Pregunta), 
	FOREIGN KEY(Id_Categoria) REFERENCES Categorias(Id_Categoria)
);

Create Table Opciones(
	Id_Opcion int NOT NULL AUTO_INCREMENT,
	Id_Pregunta int,
	Opcion varchar(255),
	Correcta boolean,
	PRIMARY KEY(Id_Opcion), 
	FOREIGN KEY(Id_Pregunta) REFERENCES Preguntas(Id_Pregunta)
);

Create Table Users(
	ID int NOT NULL AUTO_INCREMENT,
	Username varchar(255),
	Mail varchar(255),
	Contra varchar(255),
	PuntajeMax Int,
    PRIMARY KEY(ID)
);

Insert into Categorias (Id_Categoria, Nombre)
Values
('His', 'Historia'),
('Gam', 'VideoJuegos'),
('SyP', 'Series y Pelis'),
('Mus', 'Musica'),
('Pop', 'Cultura Pop'),
('Cie', 'Ciencia'),
('Ani', 'Anime')
;

Insert into Preguntas (Id_Categoria, Pregunta)
Values
('CIE', '¿Cuál es el planeta más grande del sistema solar?'),
('CIE', '¿Qué celula transporta oxígeno en la sangre?'),
('CIE', '¿Que órgano produce insulina?'),
('CIE', '¿Cuántas vértebras posee el ser humano adulto promedio?'),
('CIE', '¿Cuál de estos animales es un mamífero?'),
('CIE', '¿Cuál es el estado más común de la materia en el universo?'),
('CIE', '¿Qué parte del cuerpo controla todo el sistema nervioso?'),
('CIE', '¿Cuál es la unidad de medida de la energía?'),
('CIE', '¿Qué fuerza nos mantiene en el suelo?'),
('CIE', '¿Cuál es la fórmula del agua?'),
('CIE', '¿Quien propuso la teoria de la relatividad?'),
('CIE', '¿Quienes desarrollaron la teoria de la evolucion?'),
('CIE', '¿Que particula subatomica tinene carga negativa?'),
('CIE', '¿Cual es el hueso mas largo del cuerpo humano?'),
('CIE', '¿Cual es el proceso por el cual las plantas producen su alimento?'),
('HIS', '¿En que año comenzo la Segunda Guerra Mundial?'),
('HIS', '¿Que civilizacion construyo Machu Picchu?'),
('HIS', '¿Que evento se conmemora el 14 de julio en Francia?'),
('HIS', '¿Que provoco la Revolucion Francesa?'),
('HIS', '¿Que paises firmaron el Tratado de Versalles?'),
('HIS', '¿Que paises formaban el Eje en la Segunda Guerra Mundial?'),
('HIS', '¿En que año llego Cristobal Colon a America?'),
('HIS', '¿De que pais era Adolf Hitler?'),
('HIS', '¿Quien es Kim Jong-Un?'),
('HIS', '¿Quien fue el libertador de Argentina, Chile, Peru?'),
('HIS', '¿Que hecho dio inicio a la Revolucion Francesa?'),
('HIS', '¿Quien escribio el "Contrato Social"?'),
('HIS', '¿Quien fue el primer presidente de los Estados Unidos?'),
('HIS', '¿Que revolucion llevo a Lenin al poder?'),
('HIS', 'Segun la leyenda, ¿Quienes fundaron la ciudad de Roma?'),
('SYP', '¿Quien interpreta a Deadpool?'),
('SYP', '¿Quien es el protagonista de la serie "El Principe del Rap"?'),
('SYP', '¿Como se llama el robot gigante de "Grandes Heroes"?'),
('SYP', '¿En cual de estas series animadas el protagonista es un actor en Hollywood?'),
('SYP', '¿Cual fue la primera pelicula en ser animada completamente por computadora?'),
('SYP', '¿De que color es el gorro de papa pitufo?'),
('SYP', '¿Que pelicula gano el oscar a Mejor Pelicula Animada en 2003?'),
('SYP', '¿Que pelicula dirigida por Stanley Kubrick fue prohibida en Reino Unida por casi 30 años?'),
('SYP', '¿Quien interpreta al Joker en "The Dark Knight"?'),
('SYP', '¿Cual de estas peliculas esta ambientada en la Segunda Guerra Mundial?'),
('SYP', '¿Quien interpreta a Sherlock Holmes en la serie "Sherlock"?'),
('SYP', '¿Que pelicula animada hace una fuerte critica al capitalismo?'),
('SYP', '¿Quien es el director de Hogwarts?'),
('SYP', '¿Cual es el nombre del mundo donde ocurre la pelicula "Avatar"?'),
('SYP', '¿En que pais se produjo el primer largometraje animado?'),
('MUS', '¿Cual es el verdadero nombre de David Bowie?'),
('MUS', '¿En que pais se origino el tango?'),
('MUS', '¿Que cantante lanzo el album "Lemonade"?'),
('MUS', '¿Que banda popularizo el genero Grunge en los 90?'),
('MUS', '¿A que banda pertenece el album "Never mind the Bollocks"?'),
('MUS', '¿Quien fue el primer bajista de The Clash?'),
('MUS', '¿Que banda punk incluia en sus letras temas de ciencia ficcion y horror?'),
('MUS', '¿Que banda fue formada por Simon Cowell en "The X Factor"?'),
('MUS', '¿Que banda pop sueca gano Eurovision en 1974?'),
('MUS', '¿Cual de estas cantantes lanzo su carrera en Disney Channel antes de hacerse artista pop?'),
('MUS', '¿Que album lanzo Billie Eilish en 2021?'),
('MUS', '¿Quien es la aerisra con mas premios Grammy ganados en la historia?'),
('MUS', '¿A que tema pertenece la lirica "My loneliness is killing me"?'),
('MUS', '¿Que cantante logro exito mundia lcon el album "Let Go" en 2002?'),
('MUS', '¿Quien tiene una cancion en conjunto con Wyclef Jean?'),
('POP', '¿Cuál es la película con mayor recaudación de todos los tiempos?'),
('POP', '¿Quién interpretó al personaje de Tony Stark en el Universo Cinematográfico de Marvel?'),
('POP', '¿En qué año se estrenó la serie de televisión "Game of Thrones" en HBO?'),
('POP', '¿Quienes cometieron la masacre de Columbine?'),
('POP', '¿Qué artista lanzó el álbum "The Marshall Mathers LP" en 2000?'),
('POP', '¿Qué popular sitio de redes sociales fue lanzado en 2004 por Mark Zuckerberg?'),
('POP', '¿Cuál es el planeta más pequeño de nuestro sistema solar?'),
('POP', '¿En qué país se usó la primera bomba atómica?'),
('POP', '¿A qué desafortunado grupo pertenecen Amy Winehouse, Jimi Hendrix y Janis Joplin?'),
('POP', '¿Quién es la persona más joven en ganar un premio Grammy al Álbum del Año?'),
('POP', '¿Quién pintó a la Mona Lisa?'),
('POP', '¿Quién inventó la bombilla?'),
('POP', '¿Cual es la capital de Austria?'),
('POP', '¿Cuál es el órgano más grande del cuerpo humano?'),
('POP', '¿Cuántas veces ha estado el hombre en la Luna?'),
('GAM', '¿Que compañia desarrollo la consola Playstation?'),
('GAM', '¿A que compañia pertenece la saga Halo?'),
('GAM', '¿Cual de estos personajes aparece en todos los Super Smash Bros hasta la fecha?'),
('GAM', '¿En que año se lanzo la primera entrega de Dark Souls?'),
('GAM', '¿Que famoso diseñador de videojuegos creo Metal Gear Solid?'),
('GAM', '¿Que franquicia tiene como antagonista principal a Sephiroth?'),
('GAM', '¿Cual de estos videojuegos contiene personajes de Disney?'),
('GAM', '¿Que franquicia se centra en asesinos a lo largo de distintas epocas historicas?'),
('GAM', '¿Cuál es el videojuego más vendido de todos los tiempos?'),
('GAM', '¿Cuál fue el primer juego 3D de la historia?'),
('GAM', '¿Qué compañía inventó la primera consola de videojuegos?'),
('GAM', '¿Cual es la comida favorita de Sonic?'),
('GAM', '¿Cual de estos NO es un estilo de pelea de Kazuma Kiryu en Yakuza Kiwami?'),
('GAM', '¿Como se llama el protagonista de Hotline Miami?'),
('GAM', '¿Cual de estos videojuegos es un mundo abierto con dinosaurios?'),
('ANI', '¿Cual es la cancion debut de la banda Roselia?'),
('ANI', '¿Cual fue el nombre temporal de la banda Togenashi Togeari?'),
('ANI', '¿En que año se estreno el primer anime de Dragon Ball?'),
('ANI', '¿Como se llama el barco pirata de Luffy?'),
('ANI', '¿Cual es el nombre de las cartas que aparecen en Sakura Cardcaptor?'),
('ANI', '¿Por que Homura repite multiples veces la linea temporal?'),
('ANI', '¿Cual es el nombre del primer ending del anime K-ON?'),
('ANI', '¿Cual es el objetivo principal de Edward en Fullmetal Alchemist?'),
('ANI', '¿Cual es el nombre del demonio que posee a Inuyasha?'),
('ANI', '¿Cuantas veces falló Naruto en el examen de graduación de la Academia?'),
('ANI', '¿Cual es la cancion que salvo a la franquicia Love Live?'),
('ANI', '¿Cual es el objetivo de Kaguya y Shirogane en el anime Kaguya-sama Love is War?'),
('ANI', '¿Quien usa el seudonimo de Oblivionis durante los conciertos en Ave Mujica?'),
('ANI', '¿Que maldicion tiene Ranma Saotome?'),
('ANI', '¿Cuantas loops temporales se deduce que hizo Daiba Nana?')
;

Insert into Opciones (Id_Pregunta, Opcion, Correcta)
Values
(1,'Tierra',FALSE),
(1,'Marte',FALSE),
(1,'Jupiter',TRUE),
(1,'Venus',FALSE),
(2,'Neurona',FALSE),
(2,'Globulo rojo',TRUE),
(2,'Plaqueta',FALSE),
(2,'Globlulo Blanco',FALSE),
(3,'Corazon',FALSE),
(3,'Higado',FALSE),
(3,'Riñon',FALSE),
(3,'Pancreas',TRUE),
(4,'22',FALSE),
(4,'39',FALSE),
(4,'26',TRUE),
(4,'31',FALSE),
(5,'Cocodrilo',FALSE),
(5,'Delfin',TRUE),
(5,'Pinguino',FALSE),
(5,'Tiburon',FALSE),
(6,'Gas',FALSE),
(6,'Solido',FALSE),
(6,'Plasma',TRUE),
(6,'Liquido',FALSE),
(7,'Cerebro',TRUE),
(7,'Estomago',FALSE),
(7,'Pulmones',FALSE),
(7,'Corazon',FALSE),
(8,'Litro',FALSE),
(8,'Metro',FALSE),
(8,'Grado',FALSE),
(8,'Joule',TRUE),
(9,'Electromagnetica',FALSE),
(9,'Atomica',FALSE),
(9,'Gravedad',TRUE),
(9,'Friccion',FALSE),
(10,'H2O2',FALSE),
(10,'H2O',TRUE),
(10,'NaCI',FALSE),
(10,'CO2',FALSE),
(11,'Galileo',FALSE),
(11,'Tesla',FALSE),
(11,'Einstein',TRUE),
(11,'Newton',FALSE),
(12,'Newton y Pascal',FALSE),
(12,'Curie y Hawking',FALSE),
(12,'Einstein y Borh',FALSE),
(12,'Darwin y Russel',TRUE),
(13,'Electron',TRUE),
(13,'Proton',FALSE),
(13,'Neutron',FALSE),
(13,'Positron',FALSE),
(14,'Humero',FALSE),
(14,'Columna vertebral',FALSE),
(14,'Femur',TRUE),
(14,'Tibia',FALSE),
(15,'Respiracion',FALSE),
(15,'Digestion',FALSE),
(15,'Evaporacion',FALSE),
(15,'Fotosintesis',TRUE),
(16,'1945',FALSE),
(16,'1932',FALSE),
(16,'1939',TRUE),
(16,'1929',FALSE),
(17,'Aztecas',FALSE),
(17,'Incas',TRUE),
(17,'Mayas',FALSE),
(17,'Toltecas',FALSE),
(18,'Toma de la Bastilla',TRUE),
(18,'Independencia de Francia',FALSE),
(18,'Coronacion de Napoleon',FALSE),
(18,'Firma del tratado de Paris',FALSE),
(19,'Guerra con Alemania',FALSE),
(19,'Crisis economica y desigualdad social',TRUE),
(19,'Descubrimiento de America',FALSE),
(19,'Muerte del Papa',FALSE),
(20,'Rusia, Japon, EEUU',FALSE),
(20,'España, Italia, Grecia',FALSE),
(20,'Alemania, Francia, Reino Unido',TRUE),
(20,'Alemania, China, Portugal',FALSE),
(21,'EEUU, China, Francia',FALSE),
(21,'Alemania, Italia, Japon',TRUE),
(21,'Alemania, Reino Unido, Rusia',FALSE),
(21,'Italia, Canada, España',FALSE),
(22,'1500',FALSE),
(22,'1482',FALSE),
(22,'1492',TRUE),
(22,'1600',FALSE),
(23,'Alemania',FALSE),
(23,'Austria',TRUE),
(23,'Italia',FALSE),
(23,'Georgia',FALSE),
(24,'Lider supremo de Corea del Norte',TRUE),
(24,'Presidente de China',FALSE),
(24,'Economista Japones',FALSE),
(24,'Politico de Corea del Sur',FALSE),
(25,'Simon Bolivar',FALSE),
(25,'Manuel Belgrano',FALSE),
(25,'Miguel Hidalgo',FALSE),
(25,'Jose de San Martin',TRUE),
(26,'La invasion a Rusia',FALSE),
(26,'La coronacion de Napoleon',FALSE),
(26,'El asesinato del Rey',FALSE),
(26,'La Toma de la Bastilla',TRUE),
(27,'Voltaire',FALSE),
(27,'Rousseau',TRUE),
(27,'Monstesquieu',FALSE),
(27,'Locke',FALSE),
(28,'Abraham Lincoln ',FALSE),
(28,'Thomas Jefferson',FALSE),
(28,'John Adams',FALSE),
(28,'George Washington',TRUE),
(29,'Revolucion Francesa',FALSE),
(29,'Revolucion Industrial',FALSE),
(29,'Revolucion Rusa',TRUE),
(29,'Revolucion Cultural',FALSE),
(30,'Julio Cesar y Pompeyo',FALSE),
(30,'Romulo y Remo',TRUE),
(30,'Marco Aurelio y Tito',FALSE),
(30,'Neron y Caligua',FALSE),
(31,'Chris Evans',FALSE),
(31,'Robert Downey Jr.',FALSE),
(31,'Ryan Reynolds',TRUE),
(31,'Hugh Jackman',FALSE),
(32,'Carlton Banks',FALSE),
(32,'DJ Jazzy',FALSE),
(32,'Geoffrey',FALSE),
(32,'Will Smith',TRUE),
(33,'Megabot',FALSE),
(33,'Baymax',TRUE),
(33,'Tadashi',FALSE),
(33,'Z-13',FALSE),
(34,'BoJack Horseman',TRUE),
(34,'South Park',FALSE),
(34,'Rick y Morty',FALSE),
(34,'Futurama',FALSE),
(35,'Toy Story',TRUE),
(35,'Shrek',FALSE),
(35,'Bichos',FALSE),
(35,'Como entrenar a tu dragon',FALSE),
(36,'Rojo',TRUE),
(36,'Blanco',FALSE),
(36,'Verde',FALSE),
(36,'Amarillo',FALSE),
(37,'El viaje de Chihiro',TRUE),
(37,'Buscando a Nemo',FALSE),
(37,'Barbie en El lago de los cisnes',FALSE),
(37,'Atlantis: El regreso de Milo',FALSE),
(38,'La naranja mecanica',TRUE),
(38,'Eyes Wide Shut',FALSE),
(38,'Full Metal Jacket',FALSE),
(38,'El Resplandor',FALSE),
(39,'Heath Ledger',TRUE),
(39,'Jack Nicholson',FALSE),
(39,'Jared Leto',FALSE),
(39,'Joaquin Phoenix',FALSE),
(40,'Bastardos sin gloria',TRUE),
(40,'Jackie Brown',FALSE),
(40,'Pulp Fiction',FALSE),
(40,'Django Unchained',FALSE),
(41,'Benedict Cumberbatch',TRUE),
(41,'Martin Freeman',FALSE),
(41,'Tom Hiddleston',FALSE),
(41,'David Tennant',FALSE),
(42,'Robots',TRUE),
(42,'Lo que el agua se llevo',FALSE),
(42,'Bee Movie',FALSE),
(42,'El Espanta Tiburones',FALSE),
(43,'Albus Dumbledore',TRUE),
(43,'Severus Snape',FALSE),
(43,'Lord Voldemort ',FALSE),
(43,'Sirius Black',FALSE),
(44,'Pandora',TRUE),
(44,'Asgard',FALSE),
(44,'Westeros',FALSE),
(44,'Krypton',FALSE),
(45,'Argentina',TRUE),
(45,'Estados Unidos',FALSE),
(45,'Canadá ',FALSE),
(45,'Uruguay',FALSE),
(46,'David Robert Jones',TRUE),
(46,'Richard Starkey',FALSE),
(46,'Robert Zimmerman',FALSE),
(46,'Declan MacManus',FALSE),
(47,'Argentina',TRUE),
(47,'Chile',FALSE),
(47,'España',FALSE),
(47,'Mexico',FALSE),
(48,'Taylor Swift',TRUE),
(48,'Doja Cat',FALSE),
(48,'Cardi B',FALSE),
(48,'Dua Lipa',FALSE),
(49,'Nirvana',TRUE),
(49,'Pear Jam',FALSE),
(49,'Soundgarden',FALSE),
(49,'Alice in Chains',FALSE),
(50,'Sex Pistols',TRUE),
(50,'The Clash',FALSE),
(50,'Ramones',FALSE),
(50,'Dead Kennedys',FALSE),
(51,'Paul Sinomon',TRUE),
(51,'Mick Jones',FALSE),
(51,'Joe Strummer',FALSE),
(51,'Glen Matlock',FALSE),
(52,'The Misfits',TRUE),
(52,'The Stooges',FALSE),
(52,'The Damned',FALSE),
(52,'Husker Du',FALSE),
(53,'One Direction',TRUE),
(53,'Take That',FALSE),
(53,'Westlife',FALSE),
(53,'5 Seconds of Summer',FALSE),
(54,'ABBA',TRUE),
(54,'Ace of Base',FALSE),
(54,'Roxette',FALSE),
(54,'A-Ha',FALSE),
(55,'Demi Lovato',TRUE),
(55,'Lorde',FALSE),
(55,'Bebe Rexha',FALSE),
(55,'Charli XCX',FALSE),
(56,'Happier Than Ever',TRUE),
(56,"Don't Smile at Me",FALSE),
(56,'When We All Fall Asleep, Where Do We Go?',FALSE),
(56,'Everything I Wanted',FALSE),
(57,'Beyonce',TRUE),
(57,'Adele',FALSE),
(57,'Taylor Swift',FALSE),
(57,'Whitney Houston',FALSE),
(58,'...Baby One More Time',TRUE),
(58,'Stronger',FALSE),
(58,'Lucky',FALSE),
(58,'Toxic',FALSE),
(59,'Avril Lavigne',TRUE),
(59,'Nelly Furtado',FALSE),
(59,'Carly Rae Jepsen',FALSE),
(59,'Alanis Morissette',FALSE),
(60,'Shakira',TRUE),
(60,'Thalia',FALSE),
(60,'Jennifer Lopez',FALSE),
(60,'Paulina Rubio',FALSE),
(61,'Avatar ',TRUE),
(61,'Avengers: Endgame',FALSE),
(61,'Titanic',FALSE),
(61,'Jurassic World',FALSE),
(62,'Robert Downer Jr.',TRUE),
(62,'Mark Ruffalo',FALSE),
(62,'Tom Hiddleston',FALSE),
(62,'Samuel L. Jackson',FALSE),
(63,'2011',TRUE),
(63,'2012',FALSE),
(63,'2010',FALSE),
(63,'2009',FALSE),
(64,'Eric Harris y Dylan Klebold',TRUE),
(64,'Eric Harris y Randy Earl Matthews',FALSE),
(64,'James Osmanson y Jose Reyes',FALSE),
(64,'Artyom Anoufriev y Nikita Lytkin',FALSE),
(65,'Eminen',TRUE),
(65,'Kanye West',FALSE),
(65,'Kendric Lamar',FALSE),
(65,'Drake',FALSE),
(66,'Facebook',TRUE),
(66,'Snapchat',FALSE),
(66,'Instragram',FALSE),
(66,'Twitter',FALSE),
(67,'Mercurio',TRUE),
(67,'Marte',FALSE),
(67,'Venus',FALSE),
(67,'Neptuno',FALSE),
(68,'Japon ',TRUE),
(68,'Corea',FALSE),
(68,'Indonesia',FALSE),
(68,'China',FALSE),
(69,'Club de los 27',TRUE),
(69,'Club del Rock Tragico',FALSE),
(69,'Leyendas del Jazz oscuro',FALSE),
(69,'Club de los 24',FALSE),
(70,'Billie Eilish',TRUE),
(70,'Norah Jones',FALSE),
(70,'Taylor Swift',FALSE),
(70,'Lorde',FALSE),
(71,'Leonardo Da Vinci',TRUE),
(71,'Sandro Botticelli',FALSE),
(71,'Miguel Angel',FALSE),
(71,'Vincent Van Gogh',FALSE),
(72,'Thomas Edison',TRUE),
(72,'Nikola Tesla',FALSE),
(72,'Alexander Graham Bell',FALSE),
(72,'Benjamin Franklin',FALSE),
(73,'Viena',TRUE),
(73,'Zurich',FALSE),
(73,'Canberra',FALSE),
(73,'Wellington',FALSE),
(74,'Piel',TRUE),
(74,'Higado',FALSE),
(74,'Cerebro',FALSE),
(74,'Pulmon',FALSE),
(75,'6 veces',TRUE),
(75,'3 veces',FALSE),
(75,'12 veces',FALSE),
(75,'9 veces',FALSE),
(76,'SONY',TRUE),
(76,'Microsoft',FALSE),
(76,'Sega',FALSE),
(76,'Nintendo',FALSE),
(77,'Microsoft',TRUE),
(77,'Activision',FALSE),
(77,'EA Sports',FALSE),
(77,'CAPCOM',FALSE),
(78,'Melonpulta',TRUE),
(78,'Pinchohierba',FALSE),
(78,'Mazorcañon',FALSE),
(78,'Margarita',FALSE),
(79,'2011',TRUE),
(79,'2012',FALSE),
(79,'2014',FALSE),
(79,'2013',FALSE),
(80,'Hideo Kojima',TRUE),
(80,'Shigeru Miyamoto',FALSE),
(80,'Hideata Miyazaki',FALSE),
(80,'Will Wright',FALSE),
(81,'Final Fantasy',TRUE),
(81,'Kingdom Hearts',FALSE),
(81,'Dragon Quest',FALSE),
(81,'The Legend of Zelda',FALSE),
(82,'Kingdom Hearts',TRUE),
(82,'The Witcher 3',FALSE),
(82,'Dragon Age',FALSE),
(82,'Super Smash Bros',FALSE),
(83,"Assasin's Creed",TRUE),
(83,'Hitman',FALSE),
(83,'Devil May Cry',FALSE),
(83,'Yakuza',FALSE),
(84,'Minecraft',TRUE),
(84,'The Sims',FALSE),
(84,'Super Mario Bros',FALSE),
(84,'Mario Kart',FALSE),
(85,'3.333.360 puntos',TRUE),
(85,'16.000 puntos',FALSE),
(85,'2.555.540 puntos',FALSE),
(85,'1.110.164 puntos',FALSE),
(86,'Markus Persson',TRUE),
(86,'Gabe Newell',FALSE),
(86,'Tetsuya Nomura',FALSE),
(86,'Jade Raymond',FALSE),
(87,'Chili dogs',TRUE),
(87,'Hotdogs',FALSE),
(87,'Pizza',FALSE),
(87,'Hamburguesa',FALSE),
(88,'Dragon of Kansai',TRUE),
(88,'Brawler',FALSE),
(88,'Rush',FALSE),
(88,'Beat',FALSE),
(89,'Jacket',TRUE),
(89,'Manny Pardo',FALSE),
(89,'Tony',FALSE),
(89,'Alex',FALSE),
(90,'Ark',TRUE),
(90,'Far Cry',FALSE),
(90,'Tomb Raider',FALSE),
(90,'Horizon Forbidden West',FALSE),
(91,'BLACK SHOUT',TRUE),
(91,'FIRE BIRD',FALSE),
(91,'Song I am',FALSE),
(91,'Neo-Aspect',FALSE),
(92,'Shin-Kawasaki',TRUE),
(92,'Dream Girls',FALSE),
(92,'Undine',FALSE),
(92,'Chocolate',FALSE),
(93,'1986',TRUE),
(93,'1992',FALSE),
(93,'1995',FALSE),
(93,'1983',FALSE),
(94,'Thousand Sunny',TRUE),
(94,'Utan Sonar',FALSE),
(94,'Thriller Bark',FALSE),
(94,'Bezan Black',FALSE),
(95,'Cartas Clow',TRUE),
(95,'Bakugan',FALSE),
(95,'Cartas Spell',FALSE),
(95,'Karuta',FALSE),
(96,'Para salvar a Madoka de su tragico destino',TRUE),
(96,'Para mejorar sus habilidades',FALSE),
(96,'Para evitar pelear contra Walpurgis',FALSE),
(96,'Para convertirse en una bruja',FALSE),
(97,"Don't Say Lazy",TRUE),
(97,'Listen!!',FALSE),
(97,'Singing',FALSE),
(97,'GO GO MANIAC',FALSE),
(98,'Recuperar su cuerpo y el de su hermano',TRUE),
(98,'Vengar a su familia',FALSE),
(98,'Ser el alquimista mas poderoso',FALSE),
(98,'Encontrar la piedra filosofal',FALSE),
(99,'Naraku',TRUE),
(99,'Sesshomaru',FALSE),
(99,'Kagome',FALSE),
(99,'Kyubey',FALSE),
(100,'3 veces',TRUE),
(100,'6 veces',FALSE),
(100,'2 veces',FALSE),
(100,'1 vez',FALSE),
(101,'Snow Halation',TRUE),
(101,'Bokura no LIVE Kimi to no LIFE',FALSE),
(101,'Natsu egao 1,2 Jump',FALSE),
(101,'Wonderful Rush',FALSE),
(102,'Hacer que el otro se confiese primero',TRUE),
(102,'Casarse antes de graduarse',FALSE),
(102,'Proteger a la escuela de la corrupcion',FALSE),
(102,'Ganar el puesto de mejor estudiante',FALSE),
(103,'Togawa Sakiko',TRUE),
(103,'Yahata Umiri',FALSE),
(103,'Yuutenji Nyamu',FALSE),
(103,'Misumi Uika',FALSE),
(104,'Transformarse en mujer al tocar agua fria',TRUE),
(104,'Transformarse en un panda con la lluvia',FALSE),
(104,'Pierde su voz al tocar agua fria',FALSE),
(104,'Se transforma en gato al tocar agua fria',FALSE),
(105,'Alrededor de 60 veces',TRUE),
(105,'Menos de 20 veces',FALSE),
(105,'Mas de 100 veces',FALSE),
(105,'Alrededor de 30 veces',FALSE)
;

Insert into Users (Username, Mail, Contra, PuntajeMax)
Values
('GPallavicini', 'gpallavicini@pioix.edu.ar', 'Pepito20', 0),
('Bola Chong', 'pchong@pioix.edu.ar', 'Towa69', 0),
('SeGiFer', 'sgilfernandez@pioix.edu.ar', 'Peron2027', 0),
('MorVega', 'mvega@pioix.edu.ar', 'Kilowatt31', 0),
('a', 'facil@acceso.com.ar', '1', 1)
;
